### ISSUE TITLE
investigate wget download corruption

### ISSUE THREAD

**Issue by gmlewis** [tractordev/apptron#162]
Just for fun, I attempted to install the MoonBit compiler toolchain in an apptron app using the `curl` script provided here:
https://www.moonbitlang.com/download#moonbit-cli-tools

I discovered a few things:
* apptron uses `wget` not `curl`
* apptron uses `/bin/sh` not `/bin/bash`
* apptron Linux identifies itself as `i686` not `x86_64`

So I manually downloaded the install script to my local laptop and then addressed all these issues and made a new script
that I then uploaded to apptron using `cat > unix.sh`.

When I ran that script, it almost seemed that the download took increasingly longer time as the download size increased.
I got tired and decided to let it run overnight, so I don't know how long the 47.1MB download took, but it did appear to finish
and moved on to the next step which is to extract the gzipped tar file.

Unfortunately, it said that the file was corrupted. I attempted to manually extract it, but got the same thing.

Here's what the apptron session looked like:

```
gmlewis:~/moon-experiment $ chmod 755 unix.sh
gmlewis:~/moon-experiment $ ./unix.sh
Downloading moonbit ...
Connecting to cli.moonbitlang.com (18.161.6.42:443)
saving to '/home/gmlewis/moonbit.tar.gz'
moonbit.tar.gz       100% |********************************| 47.1M  0:00:00 ETA
'/home/gmlewis/moonbit.tar.gz' saved
tar: corrupted data
tar: short read
error: Failed to extract moonbit to "/home/gmlewis/.moon"
gmlewis:~/moon-experiment $ ls -l
total 0
-rwxr-xr-x    0 root     root          7042 Nov  5 02:14 unix.sh
gmlewis:~/moon-experiment $ cd
gmlewis:~ $ ls -l
total 0
drwxr-xr-x    0 root     root             0 Nov  5 01:51 go-experiment
drwxr-xr-x    0 root     root             0 Nov  5 02:00 moon-experiment
-rw-r--r--    0 root     root      49421341 Nov  5 02:32 moonbit.tar.gz
gmlewis:~ $ tar tf moonbit.tar.gz 
./
./lib/
./lib/runtime_core.c
./lib/libtcc1.a
./lib/libmoonbitrun.o
./lib/runtime.c
./lib/runmain.o
./include/
./include/moonbit.h
./include/moonbit-fundamental.h
./bin/
./bin/moonlex.wasm
./bin/moonyacc.wasm
./bin/moonfmt
tar: corrupted data
tar: short read
gmlewis:~ $ sha256sum moonbit.tar.gz 

```

(The `sha256sum` command never finished.)

Here's what my laptop said:

```
glenn@glenn-MacM2Pro ~/Downloads  $ sha256sum moonbit.tar.gz
c8b1b39daedb64d3fa55364aeafc2d7e74d01564468b1a7145c3369742e6471b  moonbit.tar.gz
glenn@glenn-MacM2Pro ~/Downloads  $ ls -l moonbit.tar.gz
-rw-r--r--@ 1 glenn  staff  49421341 Nov  5 13:52 moonbit.tar.gz
```

So at least the file sizes were the same.

**Comment by gmlewis** [comment]
(Please ignore my last update... I failed to update the destination dir properly in the script so the facts were wrong and I deleted the update.)

I updated the script to use `/tmp` and the difference was dramatic! The 47.1M download took less than 1 minute to `/tmp`... amazing!

Now `tar` is attempting to extract the `.tar.gz` file to my `$HOME` directory and it is much slower.
30 minutes later, and it is still trying to extract the gzipped tar. I'll let it run overnight.

**Comment by progrium** [comment]
your home dir is also not a normal filesystem. if you could extract back in /tmp we can at least close some possibilities relating to `tar: corrupted data` `tar: short read`. does the checksum work when downloading in /tmp? curious if the download is fine.

**Comment by lalyos** [comment]
The explorer "root" showing your files in the project dir instead of you HOME.
In your case the project dir is "go-experiment" which is visible in the url.
Also sometimes files are still missing, but hitting the refresh icon works.

**Comment by progrium** [comment]
Yes, you have to manually refresh the explorer sometimes right now. And yes, the explorer shows your project, not your home directory. And only your project and home directory are sync'd, so two different sessions can have totally different things installed. For a consistent environment outside your home and project, use `.apptron/envbuild`, though this is pretty slow atm.
